# Shadow
shadow = false;
xinerama-shadow-crop = true;
shadow-radius = 0;
shadow-opacity = 0.32;
shadow-offset-x = 10;
shadow-offset-y = 10;

# Fading
fading = false;
fade-delta = 3;
fade-in-step = 0.03;
fade-out-step = 0.03;
no-fading-openclose = false;

# Opacity
opacity-rule = [ "90:class_g = 'Alacritty'", "90:class_g = 'st-256color'",  "90:class_g = 'dunst'" ];

#Blur
#blur:
#{
#	method = "dual_kawase";
#	strength = 10;
#};

# General
backend = "glx";
vsync = true;

wintypes:
{
menu          = { shadow = false; fade = false;};
dropdown_menu = { shadow = false; fade = false;};
popup_menu    = { shadow = false; fade = false;};
utility       = { shadow = false; fade = false;};
tooltip       = { shadow = false; fade = false;};
};
shadow-exclude = "y = 0 && override_redirect = true";
