# Shadow
shadow = false;

# Fading
fading = false;

# Opacity
opacity-rule = [ "80:class_g = 'Alacritty'", "80:class_g = 'st-256color'", "90:class_g = 'dunst'" ];

#Blur
blur:
{
	method = "dual_kawase";
	strength = 6;
};

# General
refresh-rate = 0;
backend = "glx";
vsync = true;
unredir-if-possible = false;
glx-no-stencil = true;
detect-client-opacity = true;


wintypes:
{
menu          = { shadow = false; fade = false;};
dropdown_menu = { shadow = false; fade = false;};
popup_menu    = { shadow = false; fade = false;};
utility       = { shadow = false; fade = false;};
tooltip       = { shadow = false; fade = false;};
};
shadow-exclude = "y = 0 && override_redirect = true";
